[tools]
dprint = "0.47"
actionlint = "1.7"
pre-commit = "4"

uv = "0.7"

[tasks.fmt]
dir = "{{ config_root }}"
run = [
  "dprint fmt",
  "uv run --all-packages ruff format .",
  "uv run --all-packages ruff check . --fix",
]

[tasks.lint]
dir = "{{ config_root }}"
run = [
  "dprint check",
  "actionlint",
  "uvx zizmor .",
  "uv run --all-packages ruff check .",
  "uv run --all-packages mypy .",
]

[tasks.test_pubmed]
dir = "{{ config_root }}/servers/pubmed_mcp"
run = "uv run --all-packages pytest"

[tasks.test_pubtator3_mcp]
dir = "{{ config_root }}/servers/pubtator3_mcp"
run = "uv run --all-packages pytest"

[tasks.test_pubchem_mcp]
dir = "{{ config_root }}/servers/pubchem_mcp"
run = "uv run --all-packages pytest"

[tasks.test]
depends = ["test_pubmed", "test_pubtator3_mcp", "test_pubchem_mcp"]

[tasks.ci]
depends = ["lint", "test"]
