[tools]
dprint = "0.47"
actionlint = "1.7"
pre-commit = "4"

uv = "0.7"

[tasks.fmt]
run = [
  "dprint fmt",
  "uv run --all-packages ruff format .",
  "uv run --all-packages ruff check . --fix",
]

[tasks.lint]
run = [
  "dprint check",
  "actionlint",
  "uvx zizmor .",
  "uv run --all-packages ruff check .",
  "uv run --all-packages mypy .",
]

[tasks.test]
run = "uv run --all-packages pytest"

[tasks.ci]
depends = ["lint", "test"]
