[project]
name = "lifescience-mcps"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = [
  "libs/pubmed-client",
]

[dependency-groups]
dev = [
  "mypy>=1.15.0",
  "pytest>=8.3.5",
  "ruff>=0.11.11",
]

[tool.ruff]
target-version = "py312"