from enum import Enum


class Fields(str, Enum):
    AC = "ac"
    ACAS = "acas"
    AG = "ag"
    ANECDOTAL = "anecdotal"
    BIOTECHNOLOGY = "biotechnology"
    BREED = "breed"
    CA = "ca"
    CAUTION = "caution"
    CC = "cc"
    CELL_TYPE = "cell-type"
    CH = "ch"
    CHARACTERISTICS = "characteristics"
    DERIVED_FROM_SITE = "derived-from-site"
    DI = "di"
    DIN = "din"
    DIO = "dio"
    DISCONTINUED = "discontinued"
    DONOR_INFO = "donor-info"
    DOUBLING_TIME = "doubling-time"
    DR = "dr"
    DT = "dt"
    DTC = "dtc"
    DTU = "dtu"
    DTV = "dtv"
    FROM = "from"
    GENOME_ANCESTRY = "genome-ancestry"
    GROUP = "group"
    HI = "hi"
    HLA = "hla"
    ID = "id"
    IDSY = "idsy"
    INTEGRATED = "integrated"
    KARYOTYPE = "karyotype"
    KNOCKOUT = "knockout"
    MAB_ISOTYPE = "mab-isotype"
    MAB_TARGET = "mab-target"
    MISCELLANEOUS = "miscellaneous"
    MISSPELLING = "misspelling"
    MSI = "msi"
    OI = "oi"
    OMICS = "omics"
    OX = "ox"
    PART_OF = "part-of"
    POPULATION = "population"
    PROBLEMATIC = "problematic"
    RA = "ra"
    REF = "ref"
    REGISTRATION = "registration"
    RESISTANCE = "resistance"
    RL = "rl"
    RT = "rt"
    RX = "rx"
    SENESCENCE = "senescence"
    SEQUENCE_VARIATION = "sequence-variation"
    STR = "str"
    SX = "sx"
    SY = "sy"
    TRANSFORMANT = "transformant"
    VIROLOGY = "virology"
    WW = "ww"

    def __str__(self) -> str:
        return str(self.value)
